name: MSBuild

on: [push]

env:
  SOLUTION_FILE_PATH: winproject/mupen64/mupen64_2017.sln
  BUILD_CONFIGURATION: Release
  VCPKG_ROOT: ./vcpkg
  
jobs:
  build:
    runs-on: windows-2022 # dangerous

    steps:
    - uses: actions/checkout@v2


    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg integrate install

    - name: Install packages with vcpkg
      run: |
        cd vcpkg
        ./vcpkg install zlib minizip
    
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: mupen-artifact
        path: winproject/mupen64/bin/mupen64.exe
