name: MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: winproject/mupen64/mupen64_2017.sln

  BUILD_CONFIGURATION: Release 

jobs:
  build:
    runs-on: windows-2022 # dangerous

    steps:
    - uses: actions/checkout@v2


    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: vcpkg build
      uses: johnwason/vcpkg-action@v4
      id: vcpkg
      with:
        pkgs: zlib minizip
        triplet: x86-windows-release
        token: ${{ github.token }}
    
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: mupen-artifact
        path: winproject/mupen64/bin/mupen64.exe
